### ISSUE TITLE
Installation not working on a Conda Python 3.7.7 environment

### ISSUE THREAD

**Issue by tfabbri** [clstoulouse/motu-client-python#26]
Please find below the error from the execution of the command `motuclient - h` from cli. 

 ```
Traceback (most recent call last):
  File "/home/tommaso.fabbri/anaconda3/envs/casw/bin/motuclient", line 6, in <module>
    from motuclient import main
ImportError: cannot import name 'main' from 'motuclient' (/home/tommaso.fabbri/anaconda3/envs/casw/lib/python3.7/site-packages/motuclient/__init__.py)
```

I tried both the installation through pip and conda with the same outcome.  
Something is missing in `site-packages/motuclient` directory (maybe the content of `src/python` directory).  
Below you can find the installed content:

```
motuclient
|── cfg
│   ├── log.ini
│   └── messages.properties
├── __init__.py
├── motu_api.py
├── pom_version.py
├── __pycache__
│   ├── __init__.cpython-37.pyc
│   ├── motu_api.cpython-37.pyc
│   ├── pom_version.cpython-37.pyc
│   ├── stop_watch.cpython-37.pyc
│   ├── utils_cas.cpython-37.pyc
│   ├── utils_collection.cpython-37.pyc
│   ├── utils_configpath.cpython-37.pyc
│   ├── utils_html.cpython-37.pyc
│   ├── utils_http.cpython-37.pyc
│   ├── utils_log.cpython-37.pyc
│   ├── utils_messages.cpython-37.pyc
│   ├── utils_stream.cpython-37.pyc
│   └── utils_unit.cpython-37.pyc
├── stop_watch.py
├── utils_cas.py
├── utils_collection.py
├── utils_configpath.py
├── utils_html.py
├── utils_http.py
├── utils_log.py
├── utils_messages.py
├── utils_stream.py
└── utils_unit.py
```
